apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - web.yaml
  - bot.yaml

configMapGenerator:
  - name: ads-painel-config
    literals:
      - OPENCODE_BASE_URL=https://opencode.ai/zen/go/v1
      - OPENCODE_MODEL=deepseek-v4-flash
      - DB_PATH=./data/app.db

secretGenerator:
  - name: ads-painel-secret
    envs:
      - .secret.env
    type: Opaque
